export type Question = {
    id: number,
    category: string,
    maleQuestion: string,
    femaleQuestion: string,
}

export type Category = {
    title: string,
    description: string,
    punchline: string
}


export const questions: Question[] = [
    {
        id: 1,
        category: "Basics",
        maleQuestion: "Give a sensual massage to your partner?",
        femaleQuestion: "Give a sensual massage to your partner?",
    },
    {
        id: 2,
        category: "Basics",
        maleQuestion: "Get a sensual massage from your partner?",
        femaleQuestion: "Get a sensual massage from your partner?",
    },
    {
        id: 3,
        category: "Basics",
        maleQuestion: "Listen to music while having sex?",
        femaleQuestion: "Listen to music while having sex?",
    },
    {
        id: 4,
        category: "Basics",
        maleQuestion: "Talk dirty to your partner during sex?",
        femaleQuestion: "Talk dirty to your partner during sex?",
    },
    {
        id: 5,
        category: "Basics",
        maleQuestion: "Have your partner talk dirty to you during sex?",
        femaleQuestion: "Have your partner talk dirty to you during sex?",
    },
    {
        id: 6,
        category: "Basics",
        maleQuestion: "Be louder and more vocal during sex?",
        femaleQuestion: "Be louder and more vocal during sex?",
    },
    {
        id: 7,
        category: "Basics",
        maleQuestion: "Have your partner be louder during sex?",
        femaleQuestion: "Have your partner be louder during sex?",
    },
    {
        id: 8,
        category: "Basics",
        maleQuestion: "Have sex without using protection?",
        femaleQuestion: "Have sex without using protection?",
    },
    {
        id: 9,
        category: "Basics",
        maleQuestion: "Pull out?",
        femaleQuestion: "Have your partner pull out?",
    },
    {
        id: 10,
        category: "Basics",
        maleQuestion: "Cum inside your partner?",
        femaleQuestion: "Have your partner cum inside you?",
    },
    {
        id: 11,
        category: "Basics",
        maleQuestion: "Cum on your partner's face?",
        femaleQuestion: "Have your partner cum on your face?",
    },
    {
        id: 12,
        category: "Basics",
        maleQuestion: "Cum on your partner's chest and stomach?",
        femaleQuestion: "Have your partner cum on your chest and stomach?",
    },
    {
        id: 13,
        category: "Basics",
        maleQuestion: "Titty fuck your partner?",
        femaleQuestion: "Have your partner titty fuck you?",
    },
    {
        id: 14,
        category: "Basics",
        maleQuestion: "Receive oral sex?",
        femaleQuestion: "Receive oral sex?",
    },
    {
        id: 15,
        category: "Basics",
        maleQuestion: "Give your partner oral sex?",
        femaleQuestion: "Give your partner oral sex?",
    },
    {
        id: 16,
        category: "Basics",
        maleQuestion: "Have your partner swallow your cum?",
        femaleQuestion: "Swallow your partner's cum?",
    },
    {
        id: 17,
        category: "Role Play",
        maleQuestion: "Role-play or wear costumes during sex?",
        femaleQuestion: "Role-play or wear costumes during sex?",
    },
    {
        id: 18,
        category: "Role Play",
        maleQuestion: "Engage in Consensual Non-Consent?",
        femaleQuestion: "Engage in Consensual Non-Consent?",
    },
    {
        id: 19,
        category: "Role Play",
        maleQuestion: "Pretend you or your partner are much older?",
        femaleQuestion: "Pretend you or your partner are much older?",
    },
    {
        id: 20,
        category: "Role Play",
        maleQuestion: "Pretend you or partner are much younger?",
        femaleQuestion: "Pretend you or partner are much younger?",
    },
    {
        id: 21,
        category: "Role Play",
        maleQuestion: "Have your partner cross dress?",
        femaleQuestion: "Have your partner cross dress?",
    },
    {
        id: 22,
        category: "Role Play",
        maleQuestion: "Cross dress?",
        femaleQuestion: "Cross dress?",
    },
    {
        id: 23,
        category: "Role Play",
        maleQuestion: "Teacher role-play",
        femaleQuestion: "Teacher role-play",
    },
    {
        id: 24,
        category: "Role Play",
        maleQuestion: "Nurse role-play",
        femaleQuestion: "Nurse role-play",
    },
    {
        id: 25,
        category: "Role Play",
        maleQuestion: "Boss role-play",
        femaleQuestion: "Boss role-play",
    },
    {
        id: 26,
        category: "Role Play",
        maleQuestion: "Repairman role-play",
        femaleQuestion: "Repairman role-play",
    },
    {
        id: 27,
        category: "Role Play",
        maleQuestion: "Maid role-play",
        femaleQuestion: "Maid role-play",
    },
    {
        id: 28,
        category: "Role Play",
        maleQuestion: "Pretend your partner is a complete stranger?",
        femaleQuestion: "Pretend your partner is a complete stranger?",
    },
    {
        id: 29,
        category: "Role Play",
        maleQuestion: "Fantasy RPG role-play",
        femaleQuestion: "Fantasy RPG role-play",
    },
    {
        id: 30,
        category: "Role Play",
        maleQuestion: "Sci-fi or Space Alien role-play",
        femaleQuestion: "Sci-fi or Space Alien role-play",
    },
    {
        id: 31,
        category: "Role Play",
        maleQuestion: "Harry Potter role-play",
        femaleQuestion: "Harry Potter role-play",
    },
    {
        id: 32,
        category: "Role Play",
        maleQuestion: "Star Wars role-play",
        femaleQuestion: "Star Wars role-play",
    },
    {
        id: 33,
        category: "Role Play",
        maleQuestion: "Lord of the Rings role-play",
        femaleQuestion: "Lord of the Rings role-play",
    },
    {
        id: 34,
        category: "Role Play",
        maleQuestion: "Game of Thrones role-play",
        femaleQuestion: "Game of Thrones role-play",
    },
    {
        id: 35,
        category: "Butt Stuff",
        maleQuestion: "Have anal sex?",
        femaleQuestion: "Have anal sex?",
    },
    {
        id: 36,
        category: "Butt Stuff",
        maleQuestion: "Finger your partner anally?",
        femaleQuestion: "Finger your partner anally?",
    },
    {
        id: 37,
        category: "Butt Stuff",
        maleQuestion: "Be anally fingered by your partner?",
        femaleQuestion: "Be anally fingered by your partner?",
    },
    {
        id: 38,
        category: "Butt Stuff",
        maleQuestion: "Give your partner analingus?",
        femaleQuestion: "Give your partner analingus?",
    },
    {
        id: 39,
        category: "Butt Stuff",
        maleQuestion: "Have your partner give you analingus?",
        femaleQuestion: "Have your partner give you analingus?",
    },
    {
        id: 40,
        category: "Butt Stuff",
        maleQuestion: "Have your partner peg you?",
        femaleQuestion: "Peg your partner?",
    },
    {
        id: 41,
        category: "Butt Stuff",
        maleQuestion: "Explore anally stimulating your partner?",
        femaleQuestion: "Explore anally stimulating your partner?",
    },
    {
        id: 42,
        category: "Butt Stuff",
        maleQuestion: "Explore having your partner anally stimulate you?",
        femaleQuestion: "Explore having your partner anally stimulate you?",
    },
    {
        id: 43,
        category: "Positions",
        maleQuestion: "69?",
        femaleQuestion: "69?",
    },
    {
        id: 44,
        category: "Positions",
        maleQuestion: "Try different sexual positions?",
        femaleQuestion: "Try different sexual positions?",
    },
    {
        id: 45,
        category: "Positions",
        maleQuestion: "Do it doggy-style?",
        femaleQuestion: "Do it doggy-style?",
    },
    {
        id: 46,
        category: "Positions",
        maleQuestion: "Do cowgirl?",
        femaleQuestion: "Do cowgirl?",
    },
    {
        id: 47,
        category: "Positions",
        maleQuestion: "Do reverse-cowgirl?",
        femaleQuestion: "Do reverse-cowgirl?",
    },
    {
        id: 48,
        category: "Positions",
        maleQuestion: "Do it with your partner's legs on your shoulder?",
        femaleQuestion: "Do it with your legs on your partner's shoulders?",
    },
    {
        id: 49,
        category: "Positions",
        maleQuestion: "Have your partner on top more?",
        femaleQuestion: "Have your partner on top more?",
    },
    {
        id: 50,
        category: "Positions",
        maleQuestion: "Be on top more?",
        femaleQuestion: "Be on top more?",
    },
    {
        id: 51,
        category: "Positions",
        maleQuestion: "Have sex standing up?",
        femaleQuestion: "Have sex standing up?",
    },
    {
        id: 52,
        category: "Positions",
        maleQuestion: "Install a \"sex position of the day\" app?",
        femaleQuestion: "Install a \"sex position of the day\" app?",
    },
    {
        id: 53,
        category: "Positions",
        maleQuestion: "Get a copy of the Kama Sutra?",
        femaleQuestion: "Get a copy of the Kama Sutra?",
    },
    {
        id: 54,
        category: "Positions",
        maleQuestion: "Make a sexual to-do list?",
        femaleQuestion: "Make a sexual to-do list?",
    },
    {
        id: 55,
        category: "BDSM",
        maleQuestion: "Be rougher towards your partner in the bedroom?",
        femaleQuestion: "Be rougher towards your partner in the bedroom?",
    },
    {
        id: 56,
        category: "BDSM",
        maleQuestion: "Have your partner be rougher towards you in the bedroom?",
        femaleQuestion: "Have your partner be rougher towards you in the bedroom?",
    },
    {
        id: 57,
        category: "BDSM",
        maleQuestion: "Pull your partner's hair during sex?",
        femaleQuestion: "Pull your partner's hair during sex?",
    },
    {
        id: 58,
        category: "BDSM",
        maleQuestion: "Have your hair pulled during sex?",
        femaleQuestion: "Have your hair pulled during sex?",
    },
    {
        id: 59,
        category: "BDSM",
        maleQuestion: "Bite your partner during sex?",
        femaleQuestion: "Bite your partner during sex?",
    },
    {
        id: 60,
        category: "BDSM",
        maleQuestion: "Be bitten during sex?",
        femaleQuestion: "Be bitten during sex?",
    },
    {
        id: 61,
        category: "BDSM",
        maleQuestion: "Choke your partner during sex?",
        femaleQuestion: "Choke your partner during sex?",
    },
    {
        id: 62,
        category: "BDSM",
        maleQuestion: "Be choked during sex?",
        femaleQuestion: "Be choked during sex?",
    },
    {
        id: 63,
        category: "BDSM",
        maleQuestion: "Scratch your partner during sex?",
        femaleQuestion: "Scratch your partner during sex?",
    },
    {
        id: 64,
        category: "BDSM",
        maleQuestion: "Be scratched during sex?",
        femaleQuestion: "Be scratched during sex?",
    },
    {
        id: 65,
        category: "BDSM",
        maleQuestion: "Tie-up or handcuff your partner during sex?",
        femaleQuestion: "Tie-up or handcuff your partner during sex?",
    },
    {
        id: 66,
        category: "BDSM",
        maleQuestion: "Be tied-up or handcuffed during sex?",
        femaleQuestion: "Be tied-up or handcuffed during sex?",
    },
    {
        id: 67,
        category: "BDSM",
        maleQuestion: "Explore your submissive side with your partner?",
        femaleQuestion: "Explore your submissive side with your partner?",
    },
    {
        id: 68,
        category: "BDSM",
        maleQuestion: "Have your partner explore their submissive side with you?",
        femaleQuestion: "Have your partner explore their submissive side with you?",
    },
    {
        id: 69,
        category: "BDSM",
        maleQuestion: "Have your mouth covered or gagged during sex?",
        femaleQuestion: "Have your mouth covered or gagged during sex?",
    },
    {
        id: 70,
        category: "BDSM",
        maleQuestion: "Have your partner's mouth covered or gagged during sex?",
        femaleQuestion: "Have your partner's mouth covered or gagged during sex?",
    },
    {
        id: 71,
        category: "BDSM",
        maleQuestion: "Force your partner to orgasm?",
        femaleQuestion: "Force your partner to orgasm?",
    },
    {
        id: 72,
        category: "BDSM",
        maleQuestion: "Be forced to orgasm by your partner?",
        femaleQuestion: "Be forced to orgasm by your partner?",
    },
    {
        id: 73,
        category: "BDSM",
        maleQuestion: "Edge your partner?",
        femaleQuestion: "Edge your partner?",
    },
    {
        id: 74,
        category: "BDSM",
        maleQuestion: "Have your partner edge you?",
        femaleQuestion: "Have your partner edge you?",
    },
    {
        id: 75,
        category: "BDSM",
        maleQuestion: "Be blind folded during sex?",
        femaleQuestion: "Be blind folded during sex?",
    },
    {
        id: 76,
        category: "BDSM",
        maleQuestion: "Blind fold your partner during sex?",
        femaleQuestion: "Blind fold your partner during sex?",
    },
    {
        id: 77,
        category: "BDSM",
        maleQuestion: "Use handcuffs during sex?",
        femaleQuestion: "Use handcuffs during sex?",
    },
    {
        id: 78,
        category: "BDSM",
        maleQuestion: "Participate in impact play during sex? (whip, paddle, ...)",
        femaleQuestion: "Participate in impact play during sex? (whip, paddle, ...)",
    },
    {
        id: 79,
        category: "BDSM",
        maleQuestion: "Spank or slap your partner during sex?",
        femaleQuestion: "Spank or slap your partner during sex?",
    },
    {
        id: 80,
        category: "BDSM",
        maleQuestion: "Have your partner spank or slap you during sex?",
        femaleQuestion: "Have your partner spank or slap you during sex?",
    },
    {
        id: 81,
        category: "BDSM",
        maleQuestion: "Have your partner wear leather or latex?",
        femaleQuestion: "Have your partner wear leather or latex?",
    },
    {
        id: 82,
        category: "BDSM",
        maleQuestion: "Wear leather or latex during sex?",
        femaleQuestion: "Wear leather or latex during sex?",
    },
    {
        id: 83,
        category: "BDSM",
        maleQuestion: "Pee on your partner?",
        femaleQuestion: "Pee on your partner?",
    },
    {
        id: 84,
        category: "BDSM",
        maleQuestion: "Be peed on by your partner?",
        femaleQuestion: "Be peed on by your partner?",
    },
    {
        id: 85,
        category: "BDSM",
        maleQuestion: "Explore your dominant side with your partner?",
        femaleQuestion: "Explore your dominant side with your partner?",
    },
    {
        id: 86,
        category: "BDSM",
        maleQuestion: "Have your partner explore their dominant side with you?",
        femaleQuestion: "Have your partner explore their dominant side with you?",
    },
    {
        id: 87,
        category: "Frequency & Location",
        maleQuestion: "Take nude or semi-nude pics of your partner?",
        femaleQuestion: "Take nude or semi-nude pics of your partner?",
    },
    {
        id: 88,
        category: "Frequency & Location",
        maleQuestion: "Have your partner take nude or semi-nude pics of you?",
        femaleQuestion: "Have your partner take nude or semi-nude pics of you?",
    },
    {
        id: 89,
        category: "Frequency & Location",
        maleQuestion: "Make a private sex tape together?",
        femaleQuestion: "Make a private sex tape together?",
    },
    {
        id: 90,
        category: "Frequency & Location",
        maleQuestion: "Watch porn together?",
        femaleQuestion: "Watch porn together?",
    },
    {
        id: 91,
        category: "Frequency & Location",
        maleQuestion: "Use porn to show each other things you like?",
        femaleQuestion: "Use porn to show each other things you like?",
    },
    {
        id: 92,
        category: "Frequency & Location",
        maleQuestion: "Have shower sex?",
        femaleQuestion: "Have shower sex?",
    },
    {
        id: 93,
        category: "Frequency & Location",
        maleQuestion: "Have sex when your partner is menstruating?",
        femaleQuestion: "Have sex while you are menstruating?",
    },
    {
        id: 94,
        category: "Frequency & Location",
        maleQuestion: "Have sex more often?",
        femaleQuestion: "Have sex more often?",
    },
    {
        id: 95,
        category: "Frequency & Location",
        maleQuestion: "Schedule sex?",
        femaleQuestion: "Schedule sex?",
    },
    {
        id: 96,
        category: "Frequency & Location",
        maleQuestion: "Have sex multiple times in a row?",
        femaleQuestion: "Have sex multiple times in a row?",
    },
    {
        id: 97,
        category: "Frequency & Location",
        maleQuestion: "Have morning sex?",
        femaleQuestion: "Have morning sex?",
    },
    {
        id: 98,
        category: "Frequency & Location",
        maleQuestion: "Have sex outside?",
        femaleQuestion: "Have sex outside?",
    },
    {
        id: 99,
        category: "Frequency & Location",
        maleQuestion: "Have sex in a public place?",
        femaleQuestion: "Have sex in a public place?",
    },
    {
        id: 100,
        category: "Frequency & Location",
        maleQuestion: "Have sex in a car?",
        femaleQuestion: "Have sex in a car?",
    },
    {
        id: 101,
        category: "Frequency & Location",
        maleQuestion: "Receive road head?",
        femaleQuestion: "Give road head?",
    },
    {
        id: 102,
        category: "Frequency & Location",
        maleQuestion: "Do sexual stuff while driving?",
        femaleQuestion: "Do sexual stuff while driving?",
    },
    {
        id: 103,
        category: "Frequency & Location",
        maleQuestion: "Have sex in a library?",
        femaleQuestion: "Have sex in a library?",
    },
    {
        id: 104,
        category: "Frequency & Location",
        maleQuestion: "Post your private photos or videos online?",
        femaleQuestion: "Post your private photos or videos online?",
    },
    {
        id: 105,
        category: "Frequency & Location",
        maleQuestion: "Go to a strip club together?",
        femaleQuestion: "Go to a strip club together?",
    },
    {
        id: 106,
        category: "Frequency & Location",
        maleQuestion: "Have sex around the house?",
        femaleQuestion: "Have sex around the house?",
    },
    {
        id: 107,
        category: "Frequency & Location",
        maleQuestion: "Have phone sex?",
        femaleQuestion: "Have phone sex?",
    },
    {
        id: 108,
        category: "Frequency & Location",
        maleQuestion: "Have your partner send you nude photos?",
        femaleQuestion: "Have your partner send you nude photos?",
    },
    {
        id: 109,
        category: "Frequency & Location",
        maleQuestion: "Send your partner nude photos?",
        femaleQuestion: "Send your partner nude photos?",
    },
    {
        id: 110,
        category: "Toys and Devices",
        maleQuestion: "Use a butt plug during sex?",
        femaleQuestion: "Use a butt plug during sex?",
    },
    {
        id: 111,
        category: "Toys and Devices",
        maleQuestion: "Have your partner use a butt plug during sex?",
        femaleQuestion: "Have your partner use a butt plug during sex?",
    },
    {
        id: 112,
        category: "Toys and Devices",
        maleQuestion: "Use long distance sex toys?",
        femaleQuestion: "Use long distance sex toys?",
    },
    {
        id: 113,
        category: "Toys and Devices",
        maleQuestion: "Shop at a sex store or webstore together?",
        femaleQuestion: "Shop at a sex store or webstore together?",
    },
    {
        id: 114,
        category: "Toys and Devices",
        maleQuestion: "Use toys during sex?",
        femaleQuestion: "Use toys during sex?",
    },
    {
        id: 115,
        category: "Toys and Devices",
        maleQuestion: "Use a cock ring during sex?",
        femaleQuestion: "Have your partner use a cock ring during sex?",
    },
    {
        id: 116,
        category: "Toys and Devices",
        maleQuestion: "Use a strap-on during sex?",
        femaleQuestion: "Use a strap-on during sex?",
    },
    {
        id: 117,
        category: "Toys and Devices",
        maleQuestion: "Use a dildo during sex?",
        femaleQuestion: "Use a dildo during sex?",
    },
    {
        id: 118,
        category: "Toys and Devices",
        maleQuestion: "Use nipple clamps?",
        femaleQuestion: "Use nipple clamps?",
    },
    {
        id: 119,
        category: "Toys and Devices",
        maleQuestion: "Use a vibrator during sex?",
        femaleQuestion: "Use a vibrator during sex?",
    },
    {
        id: 120,
        category: "Body Preferences",
        maleQuestion: "Body hair",
        femaleQuestion: "Body hair",
    },
    {
        id: 121,
        category: "Body Preferences",
        maleQuestion: "Hairy armpits",
        femaleQuestion: "Hairy armpits",
    },
    {
        id: 122,
        category: "Body Preferences",
        maleQuestion: "Shaved",
        femaleQuestion: "Shaved",
    },
    {
        id: 123,
        category: "Body Preferences",
        maleQuestion: "Nipple piercings",
        femaleQuestion: "Nipple piercings",
    },
    {
        id: 124,
        category: "Body Preferences",
        maleQuestion: "Body piercings",
        femaleQuestion: "Body piercings",
    },
    {
        id: 125,
        category: "Body Preferences",
        maleQuestion: "Face piercings",
        femaleQuestion: "Face piercings",
    },
    {
        id: 126,
        category: "Body Preferences",
        maleQuestion: "Face tattoos",
        femaleQuestion: "Face tattoos",
    },
    {
        id: 127,
        category: "Body Preferences",
        maleQuestion: "Body tattoos",
        femaleQuestion: "Body tattoos",
    },
    {
        id: 128,
        category: "Body Preferences",
        maleQuestion: "Feet",
        femaleQuestion: "Feet",
    },
    {
        id: 129,
        category: "Swingers",
        maleQuestion: "Watch your partner be penetrated by another?",
        femaleQuestion: "Watch your partner be penetrated by another?",
    },
    {
        id: 130,
        category: "Swingers",
        maleQuestion: "Be penetrated by another while your partner watches?",
        femaleQuestion: "Be penetrated by another while your partner watches?",
    },
    {
        id: 131,
        category: "Swingers",
        maleQuestion: "Watch your partner penetrate another?",
        femaleQuestion: "Watch your partner penetrate another?",
    },
    {
        id: 132,
        category: "Swingers",
        maleQuestion: "Penetrate another while your partner watches?",
        femaleQuestion: "Penetrate another while your partner watches?",
    },
    {
        id: 133,
        category: "Swingers",
        maleQuestion: "Have a three-some?",
        femaleQuestion: "Have a three-some?",
    },
    {
        id: 134,
        category: "Swingers",
        maleQuestion: "Have group sex with more than three people?",
        femaleQuestion: "Have group sex with more than three people?",
    },
    {
        id: 135,
        category: "Swingers",
        maleQuestion: "Have a sexual \"Hall Pass\" sometimes?",
        femaleQuestion: "Have a sexual \"Hall Pass\" sometimes?",
    },
    {
        id: 136,
        category: "Swingers",
        maleQuestion: "Go to a nudest resort together?",
        femaleQuestion: "Go to a nudest resort together?",
    },
    {
        id: 137,
        category: "Swingers",
        maleQuestion: "Watch your partner receive oral sex from another?",
        femaleQuestion: "Watch your partner receive oral sex from another?",
    },
    {
        id: 138,
        category: "Swingers",
        maleQuestion: "Receive oral sex while your partner watches?",
        femaleQuestion: "Receive oral sex while your partner watches?",
    },
]

export const categories: Record<string, Category> = { 
    "Basics": {
        title: "😘 Basics (22)",
        punchline: "Just the Basic Stuff",
        description: "We will cover the most common stuff here. Don't be afraid to say yes!"
    },
    "Role Play": {
        title: "🧙🏼‍♂️ Role Play (18)",
        punchline: "Adult pretend playtime",
        description: "I'll play the bass, you'll play the angler."
    },
    "Butt Stuff": {
        title: "🍩 Butt Stuff (9)",
        punchline: "Anal Play",
        description: "Questions about butt stuff! We've got your back."
    },
    "Positions": {
        title: "🧘‍♀️ Positions (13)",
        punchline: "Kama Sutra Anyone?",
        description: "Doggy style, Reverse Cowgirl, and much more!"
    },
    "BDSM": {
        title: "🤐 BDSM (32)",
        punchline: "Bondage, Discipline, Submission and Masochism",
        description: "What's so sexy about BDSM? Beats me."
    },
    "Frequency & Location": {
        title: "✈️ Frequency & Location (25)",
        punchline: "When, Where, and How Often",
        description: "Where should we meet up? See you at the library ;)"
    },
    "Toys and Devices": {
        title: "🧸 Toys & Devices (10)",
        punchline: "Toys for Playtime",
        description: "What toys sound interesting? Shopping online together is fun!"
    },
    "Body Preferences": {
        title: "🌳 Body Preferences (9)",
        punchline: "All the finest details...",
        description: "If you think Chewbacca is hairy just wait till you see my wookie."
    },
    "Swingers": {
        title: "🍍 Swingers (10)",
        punchline: "Swingers and Group Stuff",
        description: "Sharing is caring! The more the merrier!"
    },
}